version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: turborepo-template-api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/turborepo-template
      - MONGODB_URI=mongodb://mongodb:27017/turborepo-template-logs
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: turborepo-template-postgres
    environment:
      POSTGRES_DB: turborepo-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:7-alpine
    container_name: turborepo-template-mongodb
    environment:
      MONGO_INITDB_DATABASE: turborepo-template-logs
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: turborepo-template-redis
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
