name: Terraform Plan (staging)

on:
  pull_request:
    paths:
      - 'infra/terraform/**'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.6'

      - name: Terraform Init (no backend for PR safety)
        working-directory: infra/terraform/staging
        run: |
          # initialize without configuring the real backend (safe in PRs)
          terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra/terraform/staging
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/terraform/staging
        run: |
          # create a plan file for review; avoid applying in CI
          terraform plan -out=tfplan

      - name: Upload Plan Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-staging
          path: infra/terraform/staging/tfplan
