name: Terraform Apply (staging) - Manual

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply (staging)
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.6'

      - name: Terraform Init (with backend)
        working-directory: infra/terraform/staging
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform/staging
        run: |
          terraform apply -auto-approve

      - name: Post-apply notes
        run: echo "Terraform apply completed."
# NOTES:
# - Protect the `staging` environment in repository Settings -> Environments and require reviewers/approvals.
# - Store sensitive credentials in repository secrets and map them to the environment as needed.
